### ISSUE TITLE
Tool skips sdkmessageprocessingsteps

### ISSUE THREAD

**Issue by chfarr** [mkmk89/UnmanagedLayerBulkRemover#2]
the tool skips unmanaged layers on plugin steps. The getComponentTypeName is returning this componentType as **sdkMessageProcessingStep** In the filteredcomponents this is set to **SDKMessageProcessingStep** 

The condition below is never getting met so nothing happens 

![image](https://user-images.githubusercontent.com/25501996/190427160-b75b6baf-a3ae-4dcc-b881-cc50eac5e4b7.png)

Can you have a look please?

**Comment by mkmk89** [comment]
hey, thanks for spotting, I have just published a fix.
